# Generated by Django 5.2.3 on 2026-07-05 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_userprofile_delete_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={},
        ),
    ]
